### ISSUE TITLE
Module '"nestjs-puregram"' has no exported member 'TelegramInternalMiddleware'.

### ISSUE THREAD

**Issue by AndriiTereshchuk** [kosheeta/nestjs-puregram#1]
Module '"nestjs-puregram"' has no exported member 'SessionInterface'.

**Comment by kosheeta** [comment]
https://github.com/ItzNeviKat/nestjs-puregram/blob/3c4b0ea5fec15cab2731d7d6467fb17b00743c8b/lib/index.ts#L11 экспортирует же

**Comment by kosheeta** [comment]
По SessionInterface в тексте - его надо импортировать из `@puregram/session`

**Comment by AndriiTereshchuk** [comment]
> https://github.com/ItzNeviKat/nestjs-puregram/blob/3c4b0ea5fec15cab2731d7d6467fb17b00743c8b/lib/index.ts#L11
> 
> экспортирует же

Я брал отсюда пример https://github.com/ItzNeviKat/nestjs-puregram/blob/lord/docs/05_more.md#middlewares

**Comment by kosheeta** [comment]
У меня всё работает, может версия не та?
