### ISSUE TITLE
TypeError: context.send is not a function

### ISSUE THREAD

**Issue by AndriiTereshchuk** [kosheeta/nestjs-puregram#2]
```
async callbackQuery(
    @Ctx()
    context: CallbackQueryContext & MessageContext
  ): Promise<unknown> {
    await context.send('1');
    return await context.answerCallbackQuery();
  }
```

**Comment by kosheeta** [comment]
Обращайтесь к документации puregram и смотрите примеры. У CallbackQueryContext нет метода context.send, а есть context.message.send.

Лучше не создавать кучу ишью на каждую ошибку, для вопросов по puregram есть [дискуссии](https://github.com/nitreojs/puregram/discussions) и [чат в Telegram](https://t.me/puregram_chat_ru).
